// productData.js
const products = [
  {
    id: 1,
    image:
      "https://m.media-amazon.com/images/I/71EJy5YCZJL._UF1000,1000_QL80_.jpg",
    title: "Samsung Galaxy S23 Ultra 12GB RAM + 256GB",
    currentPrice: "Rs.274,999",
    originalPrice: "Rs.299,999",
    discount: "-8%",
    rating: 4.8,
    reviews: 2100,
    badge: "Best Seller",
    brand: "Samsung",
    description:
      "Samsung Galaxy S23 Ultra with 200MP camera, Snapdragon 8 Gen 2, 12GB RAM, and 256GB storage.",
    installment: "Up to 36 months, as low as Rs. 12,000 per month",
    colorFamily: "Phantom Black",
    storageCapacity: "256GB",
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Green", code: "#4caf50" },
      { name: "Cream", code: "#f5f5dc" },
    ],
    storageOptions: ["256GB", "512GB", "1TB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 13-17 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Brand Warranty",
    },
    seller: {
      name: "Samsung Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 2,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ4Cz-D0fueez7o29_h62zg-GjwBjwhDSGzA&s",
    title: "Apple iPhone 14 Pro Max 256GB",
    currentPrice: "Rs.339,999",
    originalPrice: "Rs.359,999",
    discount: "-6%",
    rating: 4.9,
    reviews: 3500,
    badge: "Hot Deal",
    brand: "Apple",
    description:
      "Apple iPhone 14 Pro Max with Dynamic Island, A16 Bionic chip, ProMotion display, and 256GB storage.",
    installment: "Up to 24 months, as low as Rs. 15,000 per month",
    colorFamily: "Deep Purple",
    storageCapacity: "256GB",
    colors: [
      { name: "Deep Purple", code: "#301934" },
      { name: "Gold", code: "#ffd700" },
      { name: "Silver", code: "#c0c0c0" },
    ],
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-16 Sep",
        price: "Rs. 600",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 3,
    image:
      "https://fonezone.me/cdn/shop/files/Untitled_16_823d86f0-9673-4e39-b464-40b7072ab192.jpg?v=1742200920",
    title: "OnePlus 11 5G 12GB RAM + 256GB",
    currentPrice: "Rs.179,999",
    originalPrice: "Rs.189,999",
    discount: "-5%",
    rating: 4.6,
    reviews: 1200,
    badge: null,
    brand: "OnePlus",
    description:
      "OnePlus 11 5G with Snapdragon 8 Gen 2, Hasselblad cameras, 120Hz AMOLED display, and 5000mAh battery.",
    installment: "Up to 18 months, as low as Rs. 9,800 per month",
    colorFamily: "Eternal Green",
    storageCapacity: "256GB",
    colors: [
      { name: "Green", code: "#4caf50" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["128GB", "256GB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 450",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "OnePlus Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 4,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR76bRglDZjwFmqXG_zFK6Zc66_lbk5Lx0a3w&s",
    title: "Xiaomi 13 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.199,999",
    originalPrice: "Rs.219,999",
    discount: "-9%",
    rating: 4.7,
    reviews: 980,
    badge: "New Arrival",
    brand: "Xiaomi",
    description:
      "Xiaomi 13 Pro with Leica triple camera, Snapdragon 8 Gen 2, 120Hz AMOLED, and 120W HyperCharge.",
    installment: "Up to 24 months, as low as Rs. 10,500 per month",
    colorFamily: "Ceramic White",
    storageCapacity: "256GB",
    colors: [
      { name: "White", code: "#ffffff" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Faisalabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 400",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Xiaomi Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 5,
    image: "https://m.media-amazon.com/images/I/71V--WZVUIL._AC_SL1500_.jpg",
    title: "Google Pixel 7 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.229,999",
    originalPrice: "Rs.239,999",
    discount: "-4%",
    rating: 4.5,
    reviews: 1500,
    badge: null,
    brand: "Google",
    description:
      "Google Pixel 7 Pro with Tensor G2 chip, triple camera system, 120Hz OLED display, and Android 13.",
    installment: "Up to 24 months, as low as Rs. 11,500 per month",
    colorFamily: "Obsidian",
    storageCapacity: "256GB",
    colors: [
      { name: "Obsidian", code: "#0b0b0b" },
      { name: "Snow", code: "#f5f5f5" },
      { name: "Hazel", code: "#8e735b" },
    ],
    storageOptions: ["128GB", "256GB", "512GB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 550",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "1 Year Google Warranty",
    },
    seller: {
      name: "Google Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 6,
    image:
      "https://propakistani.pk/price/wp-content/uploads/2022/01/Oppo-Find-X5-Pro-price-1.png",
    title: "Oppo Find X5 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.179,999",
    originalPrice: "Rs.189,999",
    discount: "-5%",
    rating: 4.6,
    reviews: 870,
    badge: "Trending",
    brand: "Oppo",
    description:
      "Oppo Find X5 Pro with Snapdragon 8 Gen 1, Hasselblad tuned cameras, and 80W fast charging.",
    installment: "Up to 18 months, as low as Rs. 9,700 per month",
    colorFamily: "Ceramic Black",
    storageCapacity: "256GB",
    colors: [
      { name: "Black", code: "#000000" },
      { name: "White", code: "#ffffff" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Multan",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Oppo Warranty",
    },
    seller: {
      name: "Oppo Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 7,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0yTV0evoFIlbIn5e4RDX50WE0wTTouN2Mvw&s",
    title: "Vivo X90 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.169,999",
    originalPrice: "Rs.179,999",
    discount: "-6%",
    rating: 4.5,
    reviews: 720,
    badge: null,
    brand: "Vivo",
    description:
      "Vivo X90 Pro with Zeiss optics, Dimensity 9200 chip, 120Hz AMOLED display, and 120W fast charging.",
    installment: "Up to 18 months, as low as Rs. 9,000 per month",
    colorFamily: "Legendary Black",
    storageCapacity: "256GB",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["256GB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 400",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "1 Year Vivo Warranty",
    },
    seller: {
      name: "Vivo Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 8,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf18zstjKOJZOdu4VWlRt6YFH53Vz6ySC-ow&s",
    title: "Realme GT Neo 5 16GB RAM + 256GB",
    currentPrice: "Rs.119,999",
    originalPrice: "Rs.129,999",
    discount: "-8%",
    rating: 4.3,
    reviews: 610,
    badge: "Hot Deal",
    brand: "Realme",
    description:
      "Realme GT Neo 5 with Snapdragon 8+ Gen 1, 240W fast charging, and 16GB RAM performance beast.",
    installment: "Up to 12 months, as low as Rs. 10,000 per month",
    colorFamily: "Purple",
    storageCapacity: "256GB",
    colors: [{ name: "Purple", code: "#800080" }],
    storageOptions: ["128GB", "256GB"],
    deliveryInfo: {
      location: "Hyderabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 350",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "1 Year Realme Warranty",
    },
    seller: {
      name: "Realme Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 9,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4j2i6b7gt0CXmIaEuNpYOQJP9JREdjw1MIw&s",
    title: "Sony Xperia 1 IV 12GB RAM + 256GB",
    currentPrice: "Rs.199,999",
    originalPrice: "Rs.209,999",
    discount: "-5%",
    rating: 4.4,
    reviews: 540,
    badge: "Premium",
    brand: "Sony",
    description:
      "Sony Xperia 1 IV with 4K HDR OLED display, Snapdragon 8 Gen 1, and ZEISS optics for pro photography.",
    installment: "Up to 18 months, as low as Rs. 11,000 per month",
    colorFamily: "Frosted Black",
    storageCapacity: "256GB",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-16 Sep",
        price: "Rs. 600",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Sony Warranty",
    },
    seller: {
      name: "Sony Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 10,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK9DtlNDnDlQuL5HYdVIaf37QSJzbXN4eUHQ&s",
    title: "Apple iPhone 13 128GB",
    currentPrice: "Rs.189,999",
    originalPrice: "Rs.199,999",
    discount: "-5%",
    rating: 4.8,
    reviews: 4800,
    badge: "Best Seller",
    brand: "Apple",
    description:
      "iPhone 13 with A15 Bionic chip, 6.1-inch Super Retina XDR display, and advanced dual-camera system.",
    installment: "Up to 24 months, Rs. 8,500 per month",
    colorFamily: "Starlight",
    storageCapacity: "128GB",
    colors: [
      { name: "Red", code: "#ff0000" },
      { name: "Starlight", code: "#f5f5dc" },
      { name: "Blue", code: "#0000ff" },
    ],
    storageOptions: ["128GB", "256GB", "512GB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 13-17 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 11,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx9LP6gQ9PPliTjOsX60tZrR9mTPFxKF6QQw&s",
    title: "Apple iPhone 14 Pro Max 256GB",
    currentPrice: "Rs.329,999",
    originalPrice: "Rs.349,999",
    discount: "-6%",
    rating: 4.9,
    reviews: 5200,
    badge: "Best Seller",
    brand: "Apple",
    description:
      "iPhone 14 Pro Max with Dynamic Island, A16 Bionic chip, Always-On display, and 48MP Pro camera system.",
    installment: "Up to 36 months, Rs. 15,000 per month",
    colorFamily: "Deep Purple",
    storageCapacity: "256GB",
    colors: [
      { name: "Deep Purple", code: "#4b0082" },
      { name: "Gold", code: "#ffd700" },
      { name: "Silver", code: "#c0c0c0" },
    ],
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 800",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 12,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrX3P8vK9Jc6sf-qQe9DCUfVxs6GRZ6M5QgQ&s",
    title: "Samsung Galaxy Z Fold 5 12GB RAM + 512GB",
    currentPrice: "Rs.479,999",
    originalPrice: "Rs.499,999",
    discount: "-4%",
    rating: 4.7,
    reviews: 1900,
    badge: "Trending",
    brand: "Samsung",
    description:
      "Samsung Galaxy Z Fold 5 with Snapdragon 8 Gen 2, foldable AMOLED display, and multitasking powerhouse.",
    installment: "Up to 36 months, Rs. 21,000 per month",
    colorFamily: "Icy Blue",
    storageCapacity: "512GB",
    colors: [
      { name: "Blue", code: "#4682b4" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 1,000",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Samsung Warranty",
    },
    seller: {
      name: "Samsung Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 13,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1wDL0NfQa67FWXmfwa32TxIw0-XeFfkehYg&s",
    title: "Google Pixel 7 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.219,999",
    originalPrice: "Rs.229,999",
    discount: "-4%",
    rating: 4.6,
    reviews: 2800,
    badge: "Hot Deal",
    brand: "Google",
    description:
      "Google Pixel 7 Pro with Tensor G2 chip, triple camera system with 30x zoom, and clean Android 13 experience.",
    installment: "Up to 24 months, Rs. 10,500 per month",
    colorFamily: "Obsidian",
    storageCapacity: "256GB",
    colors: [
      { name: "Obsidian", code: "#1c1c1c" },
      { name: "Snow", code: "#ffffff" },
    ],
    storageOptions: ["128GB", "256GB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 700",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Google Warranty",
    },
    seller: {
      name: "Google Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 14,
    image:
      "https://cdn.salla.sa/lGvlKd/D87b5y9bFytSSYAbga1rkUcxHshY2Fw0YOlSVfWD.jpg",
    title: "OnePlus 11 16GB RAM + 256GB",
    currentPrice: "Rs.159,999",
    originalPrice: "Rs.169,999",
    discount: "-6%",
    rating: 4.5,
    reviews: 1500,
    badge: "Trending",
    brand: "OnePlus",
    description:
      "OnePlus 11 with Snapdragon 8 Gen 2, 100W fast charging, AMOLED display, and Hasselblad-tuned cameras.",
    installment: "Up to 18 months, Rs. 9,500 per month",
    colorFamily: "Eternal Green",
    storageCapacity: "256GB",
    colors: [
      { name: "Green", code: "#228b22" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["128GB", "256GB"],
    deliveryInfo: {
      location: "Multan",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year OnePlus Warranty",
    },
    seller: {
      name: "OnePlus Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 15,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgHsAlAQEqdRTCO62UrJRuo1KG6CSWjho46A&s",
    title: "Xiaomi 13 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.149,999",
    originalPrice: "Rs.159,999",
    discount: "-6%",
    rating: 4.4,
    reviews: 1100,
    badge: "Popular",
    brand: "Xiaomi",
    description:
      "Xiaomi 13 Pro with Snapdragon 8 Gen 2, Leica-powered triple cameras, and 120Hz AMOLED display.",
    installment: "Up to 18 months, Rs. 8,900 per month",
    colorFamily: "Ceramic White",
    storageCapacity: "256GB",
    colors: [
      { name: "White", code: "#ffffff" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Hyderabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 600",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Xiaomi Warranty",
    },
    seller: {
      name: "Mi Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 16,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpeC8fFanak5MpcB5XoY4AxpKgk7uYJws8fQ&s",
    title: "Asus ROG Phone 7 Ultimate 16GB RAM + 512GB",
    currentPrice: "Rs.239,999",
    originalPrice: "Rs.249,999",
    discount: "-4%",
    rating: 4.6,
    reviews: 650,
    badge: "Gaming",
    brand: "Asus",
    description:
      "Asus ROG Phone 7 Ultimate with Snapdragon 8 Gen 2, AMOLED 165Hz display, and 6000mAh battery.",
    installment: "Up to 24 months, Rs. 11,000 per month",
    colorFamily: "Storm White",
    storageCapacity: "512GB",
    colors: [
      { name: "White", code: "#ffffff" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["512GB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-16 Sep",
        price: "Rs. 800",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Asus Warranty",
    },
    seller: {
      name: "Asus Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 17,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vtMdXLxXyugxPYGZ00Ln_x6QaCOHwZq2kA&s",
    title: "Huawei P60 Pro 8GB RAM + 256GB",
    currentPrice: "Rs.139,999",
    originalPrice: "Rs.149,999",
    discount: "-7%",
    rating: 4.3,
    reviews: 500,
    badge: null,
    brand: "Huawei",
    description:
      "Huawei P60 Pro with Snapdragon 8+ Gen 1 4G, XMAGE cameras, and 88W fast charging.",
    installment: "Up to 18 months, Rs. 7,800 per month",
    colorFamily: "Rococo Pearl",
    storageCapacity: "256GB",
    colors: [
      { name: "Pearl", code: "#f5f5dc" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 600",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Huawei Warranty",
    },
    seller: {
      name: "Huawei Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 18,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9IpTX2tHR-5gQ21x6Qx9QVz9CQ-kX8ChDrw&s",
    title: "Motorola Edge 40 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.129,999",
    originalPrice: "Rs.139,999",
    discount: "-7%",
    rating: 4.2,
    reviews: 430,
    badge: "New Arrival",
    brand: "Motorola",
    description:
      "Motorola Edge 40 Pro with Snapdragon 8 Gen 2, 165Hz AMOLED display, and 125W fast charging.",
    installment: "Up to 18 months, Rs. 7,200 per month",
    colorFamily: "Lunar Blue",
    storageCapacity: "256GB",
    colors: [{ name: "Blue", code: "#4682b4" }],
    storageOptions: ["256GB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Motorola Warranty",
    },
    seller: {
      name: "Motorola Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 19,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSixgtoCz6Dedadm8pwdgvxmTw2rEd61_IzHw&s",
    title: "Apple MacBook Pro 14-inch M2 Pro",
    currentPrice: "Rs.529,999",
    originalPrice: "Rs.549,999",
    discount: "-4%",
    rating: 4.9,
    reviews: 1200,
    badge: "Best Seller",
    brand: "Apple",
    description:
      "MacBook Pro 14-inch with M2 Pro chip, Liquid Retina XDR display, and 18 hours battery life.",
    installment: "Up to 36 months, Rs. 24,000 per month",
    colorFamily: "Space Gray",
    storageCapacity: "512GB",
    colors: [
      { name: "Gray", code: "#808080" },
      { name: "Silver", code: "#c0c0c0" },
    ],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 1,200",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 20,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoShL5JAaWVnn54M9pAAmpYWow502qCp0tDQ&s",
    title: "Dell XPS 13 Plus Laptop 13th Gen i7",
    currentPrice: "Rs.389,999",
    originalPrice: "Rs.409,999",
    discount: "-5%",
    rating: 4.6,
    reviews: 870,
    badge: "Premium",
    brand: "Dell",
    description:
      "Dell XPS 13 Plus with 13th Gen Intel Core i7, InfinityEdge display, and sleek aluminum design.",
    installment: "Up to 24 months, Rs. 18,500 per month",
    colorFamily: "Platinum Silver",
    storageCapacity: "1TB",
    colors: [
      { name: "Silver", code: "#c0c0c0" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 1,000",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Dell Warranty",
    },
    seller: {
      name: "Dell Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 21,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE-ExcL1u5hyudC9jn5YAMUeERvr-zzPpVWQ&s",
    title: "HP Spectre x360 14 13th Gen i7",
    currentPrice: "Rs.369,999",
    originalPrice: "Rs.389,999",
    discount: "-5%",
    rating: 4.5,
    reviews: 720,
    badge: "Trending",
    brand: "HP",
    description:
      "HP Spectre x360 14 with Intel Evo platform, 13th Gen i7, OLED touchscreen, and 16GB RAM.",
    installment: "Up to 24 months, Rs. 17,500 per month",
    colorFamily: "Nightfall Black",
    storageCapacity: "512GB",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Multan",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 13-17 Sep",
        price: "Rs. 900",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year HP Warranty",
    },
    seller: {
      name: "HP Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 22,
    image:
      "https://p4-ofp.static.pub/fes/cms/2022/06/16/s444ye7sqwg6rv1b8on54vm77eopra543125.png",
    title: "Lenovo Legion 5 Pro AMD Ryzen 7",
    currentPrice: "Rs.299,999",
    originalPrice: "Rs.319,999",
    discount: "-6%",
    rating: 4.6,
    reviews: 940,
    badge: "Gaming",
    brand: "Lenovo",
    description:
      "Lenovo Legion 5 Pro gaming laptop with Ryzen 7 6800H, RTX 3070Ti GPU, and 165Hz display.",
    installment: "Up to 24 months, Rs. 14,000 per month",
    colorFamily: "Storm Gray",
    storageCapacity: "1TB",
    colors: [{ name: "Gray", code: "#808080" }],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 1,200",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Lenovo Warranty",
    },
    seller: {
      name: "Lenovo Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 23,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_-NATOYs22BFRR6DseNO7Tm2jb5cfFJLhsw&s",
    title: "Apple MacBook Air M2 13-inch",
    currentPrice: "Rs.289,999",
    originalPrice: "Rs.309,999",
    discount: "-6%",
    rating: 4.8,
    reviews: 3100,
    badge: "Best Seller",
    brand: "Apple",
    description:
      "MacBook Air 13-inch with M2 chip, 18-hour battery life, and ultra-thin lightweight design.",
    installment: "Up to 24 months, Rs. 13,800 per month",
    colorFamily: "Midnight",
    storageCapacity: "512GB",
    colors: [
      { name: "Midnight", code: "#191970" },
      { name: "Starlight", code: "#f8f4e3" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 13-17 Sep",
        price: "Rs. 800",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 24,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxnDv-hv2HbciKWsBNxxdqFREASICIdDpsTQ&s",
    title: "Microsoft Surface Laptop 5 13.5-inch",
    currentPrice: "Rs.319,999",
    originalPrice: "Rs.339,999",
    discount: "-6%",
    rating: 4.4,
    reviews: 520,
    badge: "Premium",
    brand: "Microsoft",
    description:
      "Microsoft Surface Laptop 5 with 13th Gen Intel Core i7, PixelSense touchscreen, and sleek design.",
    installment: "Up to 24 months, Rs. 15,200 per month",
    colorFamily: "Platinum",
    storageCapacity: "512GB",
    colors: [{ name: "Platinum", code: "#e5e4e2" }],
    storageOptions: ["512GB"],
    deliveryInfo: {
      location: "Hyderabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 1,000",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Microsoft Warranty",
    },
    seller: {
      name: "Microsoft Store",
      type: "Authorized Seller",
      chatAvailable: true,
    },
  },
  {
    id: 25,
    image:
      "https://assets2.razerzone.com/images/pnx.assets/a2c45a48832815a0cf64acd462fe9bf7/razer-blade-15-ch9-ogimage_1200x630.webp",
    title: "Razer Blade 15 Advanced Gaming Laptop",
    currentPrice: "Rs.459,999",
    originalPrice: "Rs.479,999",
    discount: "-4%",
    rating: 4.6,
    reviews: 670,
    badge: "Gaming",
    brand: "Razer",
    description:
      "Razer Blade 15 with 12th Gen Intel Core i9, RTX 3080 Ti GPU, and QHD 240Hz display.",
    installment: "Up to 36 months, Rs. 21,000 per month",
    colorFamily: "Black",
    storageCapacity: "1TB",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["1TB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 1,200",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Razer Warranty",
    },
    seller: {
      name: "Razer Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 26,
    image: "https://m.media-amazon.com/images/I/51yMS1ecBrL._AC_SL1000_.jpg",
    title: "OnePlus 11 5G 16GB RAM + 256GB",
    currentPrice: "Rs.189,999",
    originalPrice: "Rs.209,999",
    discount: "-10%",
    rating: 4.7,
    reviews: 1340,
    badge: "Top Rated",
    brand: "OnePlus",
    description:
      "OnePlus 11 5G with Snapdragon 8 Gen 2, Hasselblad cameras, 16GB RAM, and 256GB storage.",
    installment: "Up to 24 months, as low as Rs. 9,000 per month",
    colorFamily: "Titan Black",
    storageCapacity: "256GB",
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Green", code: "#4caf50" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-16 Sep",
        price: "Rs. 400",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Brand Warranty",
    },
    seller: {
      name: "OnePlus Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 27,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHFCkVV26GZVAFvfhAlRDBpuYgcz-Vn2XkYA&s",
    title: "Sony WH-1000XM5 Wireless Headphones",
    currentPrice: "Rs.89,999",
    originalPrice: "Rs.99,999",
    discount: "-10%",
    rating: 4.8,
    reviews: 1980,
    badge: "Best Seller",
    brand: "Sony",
    description:
      "Sony WH-1000XM5 Noise Cancelling Wireless Headphones with 30 hours battery life.",
    installment: "Up to 12 months, as low as Rs. 7,500 per month",
    colorFamily: "Black",
    storageCapacity: null,
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Silver", code: "#dcdcdc" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 11-14 Sep",
        price: "Rs. 350",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "6 Months Warranty",
    },
    seller: {
      name: "Sony Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 28,
    image:
      "https://appleshop.com.pk/wp-content/uploads/2022/06/macbook-air-midnight2.jpg",
    title: "Apple MacBook Air M2 (2023) 8GB RAM + 256GB",
    currentPrice: "Rs.324,999",
    originalPrice: "Rs.349,999",
    discount: "-7%",
    rating: 4.9,
    reviews: 890,
    badge: "Apple Choice",
    brand: "Apple",
    description:
      "MacBook Air M2 chip with 13.6-inch Liquid Retina Display, 8GB RAM, and 256GB SSD.",
    installment: "Up to 36 months, as low as Rs. 15,000 per month",
    colorFamily: "Starlight",
    storageCapacity: "256GB",
    colors: [
      { name: "Starlight", code: "#fff8dc" },
      { name: "Midnight", code: "#191970" },
    ],
    storageOptions: ["256GB", "512GB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 29,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbPGZtAoPpmc1ynSH2Lzwu5wzCRSdqtKqC8w&s",
    title: "Samsung 55-Inch 4K QLED Smart TV",
    currentPrice: "Rs.189,999",
    originalPrice: "Rs.219,999",
    discount: "-14%",
    rating: 4.6,
    reviews: 1560,
    badge: "Top Pick",
    brand: "Samsung",
    description:
      "Samsung 55-inch 4K QLED Smart TV with Quantum HDR and Alexa Built-in.",
    installment: "Up to 24 months, as low as Rs. 8,000 per month",
    colorFamily: "Black",
    storageCapacity: null,
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: [],
    deliveryInfo: {
      location: "Multan",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 1,000",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "2 Year Brand Warranty",
    },
    seller: {
      name: "Samsung Electronics",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 30,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4BM-EXtdV3iLBlwrv9QjoAY2-h_fmqMTjPQ&s",
    title: "Fitbit Versa 4 Fitness Smartwatch",
    currentPrice: "Rs.39,999",
    originalPrice: "Rs.49,999",
    discount: "-20%",
    rating: 4.5,
    reviews: 1345,
    badge: "Trending",
    brand: "Fitbit",
    description:
      "Fitbit Versa 4 with heart rate monitor, GPS, and 6-day battery life.",
    installment: "Up to 12 months, as low as Rs. 3,500 per month",
    colorFamily: "Pink Sand",
    storageCapacity: null,
    colors: [
      { name: "Pink", code: "#ffc0cb" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Faisalabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 10-13 Sep",
        price: "Rs. 250",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Fitbit Pakistan",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 31,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCjF5_SdVPqPkZepNF64KWkpVps3rw7BJcAA&s",
    title: "Dell XPS 13 Laptop 16GB RAM + 512GB SSD",
    currentPrice: "Rs.289,999",
    originalPrice: "Rs.319,999",
    discount: "-9%",
    rating: 4.7,
    reviews: 920,
    badge: "Best Seller",
    brand: "Dell",
    description:
      "Dell XPS 13 ultrabook with Intel Core i7, 16GB RAM, 512GB SSD and InfinityEdge Display.",
    installment: "Up to 36 months, as low as Rs. 12,000 per month",
    colorFamily: "Silver",
    storageCapacity: "512GB",
    colors: [{ name: "Silver", code: "#c0c0c0" }],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year International Warranty",
    },
    seller: {
      name: "Dell Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 32,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlnHV5PG1d8bL9nrs42sn7f6Ww-ktIc7cgVQ&s",
    title: "Logitech MX Master 3S Wireless Mouse",
    currentPrice: "Rs.24,999",
    originalPrice: "Rs.29,999",
    discount: "-17%",
    rating: 4.9,
    reviews: 1800,
    badge: "Top Rated",
    brand: "Logitech",
    description:
      "Logitech MX Master 3S ergonomic wireless mouse with fast scrolling and long battery life.",
    installment: "Up to 6 months, as low as Rs. 4,100 per month",
    colorFamily: "Graphite",
    storageCapacity: null,
    colors: [
      { name: "Graphite", code: "#2f4f4f" },
      { name: "Pale Grey", code: "#d3d3d3" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-16 Sep",
        price: "Rs. 200",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Logitech Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 33,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWFIa4Jtm1KdL3aF1oiRJk2HUpS5zKWbfaZQ&s",
    title: "PlayStation 5 Standard Edition Console",
    currentPrice: "Rs.199,999",
    originalPrice: "Rs.219,999",
    discount: "-9%",
    rating: 4.8,
    reviews: 2450,
    badge: "Best Seller",
    brand: "Sony",
    description:
      "Sony PlayStation 5 console with ultra-fast SSD, 4K gaming support, and DualSense controller.",
    installment: "Up to 24 months, as low as Rs. 9,000 per month",
    colorFamily: "White",
    storageCapacity: "825GB",
    colors: [
      { name: "White", code: "#ffffff" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-17 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Sony Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 34,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIjaXTQauEggEQJ_XxnLaZTI71d5DkE_sfCQ&s",
    title: "Canon EOS R10 Mirrorless Camera",
    currentPrice: "Rs.229,999",
    originalPrice: "Rs.249,999",
    discount: "-8%",
    rating: 4.7,
    reviews: 630,
    badge: "New Arrival",
    brand: "Canon",
    description:
      "Canon EOS R10 with 24.2MP APS-C sensor, 4K video recording, and RF lens mount.",
    installment: "Up to 24 months, as low as Rs. 10,000 per month",
    colorFamily: "Black",
    storageCapacity: "32GB SD Card Bundle",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["Body Only", "Kit Lens"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 18-21 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Canon Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 35,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR54e2t-rLjCW7WTFrnjwop8WxGRxLPUCvBw&s",
    title: "Nintendo Switch OLED Model",
    currentPrice: "Rs.92,999",
    originalPrice: "Rs.104,999",
    discount: "-11%",
    rating: 4.8,
    reviews: 2800,
    badge: "Hot Pick",
    brand: "Nintendo",
    description:
      "Nintendo Switch OLED with vibrant 7-inch display, enhanced audio, and dock support.",
    installment: "Up to 12 months, as low as Rs. 7,800 per month",
    colorFamily: "White",
    storageCapacity: "64GB",
    colors: [
      { name: "White", code: "#ffffff" },
      { name: "Neon Red/Blue", code: "#ff0000" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 13-16 Sep",
        price: "Rs. 300",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "7 days easy return",
      brandWarranty: "6 Months Warranty",
    },
    seller: {
      name: "Nintendo Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 36,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRz589utbd7yXJv8I38Z9TMnIzMcsjcF6g2w&s",
    title: "Dyson V15 Detect Cordless Vacuum Cleaner",
    currentPrice: "Rs.179,999",
    originalPrice: "Rs.199,999",
    discount: "-10%",
    rating: 4.9,
    reviews: 540,
    badge: "Luxury Pick",
    brand: "Dyson",
    description:
      "Dyson V15 Detect with laser dust detection, HEPA filtration, and 60 minutes runtime.",
    installment: "Up to 24 months, as low as Rs. 7,800 per month",
    colorFamily: "Yellow/Iron",
    storageCapacity: null,
    colors: [
      { name: "Yellow", code: "#ffd700" },
      { name: "Iron", code: "#696969" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 700",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "2 Year Warranty",
    },
    seller: {
      name: "Dyson Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 37,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRws3PvtrENy9Vd8KdcxdFDOa6Q97qcd2up-g&s",
    title: "ASUS ROG Strix Gaming Laptop 16GB + 1TB",
    currentPrice: "Rs.399,999",
    originalPrice: "Rs.439,999",
    discount: "-9%",
    rating: 4.8,
    reviews: 780,
    badge: "Gaming Beast",
    brand: "ASUS",
    description:
      "ASUS ROG Strix with Intel i9, RTX 4070, 16GB RAM and 1TB SSD. Perfect for hardcore gaming.",
    installment: "Up to 36 months, as low as Rs. 15,000 per month",
    colorFamily: "Black",
    storageCapacity: "1TB",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 17-21 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year ASUS Warranty",
    },
    seller: {
      name: "ASUS Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 38,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJhaYCBFFT3xXU9ZBgePBBG7f7IfoSGZM3A&s",
    title: "GoPro HERO11 Black Action Camera",
    currentPrice: "Rs.129,999",
    originalPrice: "Rs.139,999",
    discount: "-7%",
    rating: 4.6,
    reviews: 1340,
    badge: "Adventure Pick",
    brand: "GoPro",
    description:
      "GoPro HERO11 Black with HyperSmooth stabilization, 5.3K video and waterproof design.",
    installment: "Up to 12 months, as low as Rs. 11,000 per month",
    colorFamily: "Black",
    storageCapacity: "64GB microSD Bundle",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: [],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 400",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "GoPro Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 39,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl91o9Mk1Vb5-GVKZPqtaH_v4bQqP8U6MKSA&s",
    title: "JBL Charge 5 Portable Bluetooth Speaker",
    currentPrice: "Rs.29,999",
    originalPrice: "Rs.34,999",
    discount: "-14%",
    rating: 4.7,
    reviews: 2200,
    badge: "Music Lovers",
    brand: "JBL",
    description:
      "JBL Charge 5 speaker with deep bass, 20 hours playtime, and IP67 waterproof rating.",
    installment: "Up to 6 months, as low as Rs. 5,000 per month",
    colorFamily: "Black",
    storageCapacity: null,
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Blue", code: "#0000ff" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 13-16 Sep",
        price: "Rs. 250",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: { name: "JBL Store", type: "Official Store", chatAvailable: true },
  },
  {
    id: 40,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbz1QPSke-uSxjb1PmvdYfhyJnD5m5AGeMRg&s",
    title: "Samsung Galaxy Tab S9 Ultra 12GB RAM + 512GB",
    currentPrice: "Rs.319,999",
    originalPrice: "Rs.349,999",
    discount: "-9%",
    rating: 4.9,
    reviews: 650,
    badge: "Best Seller",
    brand: "Samsung",
    description:
      "Samsung Galaxy Tab S9 Ultra with 14.6-inch AMOLED display, Snapdragon 8 Gen 2 and S-Pen.",
    installment: "Up to 36 months, as low as Rs. 14,000 per month",
    colorFamily: "Graphite",
    storageCapacity: "512GB",
    colors: [{ name: "Graphite", code: "#2f4f4f" }],
    storageOptions: ["256GB", "512GB", "1TB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Brand Warranty",
    },
    seller: {
      name: "Samsung Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 41,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZkidE_yllYIuk9Bh_vMZ46vlolw6H-T3Gfw&s",
    title: "Apple Watch Ultra 2 GPS + Cellular",
    currentPrice: "Rs.229,999",
    originalPrice: "Rs.249,999",
    discount: "-8%",
    rating: 4.8,
    reviews: 1240,
    badge: "Luxury Watch",
    brand: "Apple",
    description:
      "Apple Watch Ultra 2 with rugged titanium case, 49mm Retina display and 36-hour battery life.",
    installment: "Up to 24 months, as low as Rs. 10,000 per month",
    colorFamily: "Titanium",
    storageCapacity: "32GB",
    colors: [
      { name: "Titanium", code: "#d2b48c" },
      { name: "Orange Band", code: "#ff8c00" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 400",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Apple Warranty",
    },
    seller: {
      name: "Apple Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 42,
    image:
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c07973484.png?imdensity=1&impolicy=Png_Res",
    title: "HP Envy x360 Convertible Laptop",
    currentPrice: "Rs.209,999",
    originalPrice: "Rs.229,999",
    discount: "-9%",
    rating: 4.6,
    reviews: 780,
    badge: "Hot Pick",
    brand: "HP",
    description:
      "HP Envy x360 2-in-1 touchscreen laptop with AMD Ryzen 7, 16GB RAM, 512GB SSD.",
    installment: "Up to 24 months, as low as Rs. 9,000 per month",
    colorFamily: "Silver",
    storageCapacity: "512GB",
    colors: [{ name: "Silver", code: "#c0c0c0" }],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Rs. 500",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year International Warranty",
    },
    seller: {
      name: "HP Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 43,
    image:
      "https://goldencamera.pk/wp-content/uploads/2025/01/1652172743_IMG_1750924.webp",
    title: "DJI Mini 3 Pro Drone with Camera",
    currentPrice: "Rs.224,999",
    originalPrice: "Rs.249,999",
    discount: "-10%",
    rating: 4.7,
    reviews: 880,
    badge: "Best Seller",
    brand: "DJI",
    description:
      "DJI Mini 3 Pro foldable drone with 4K camera, 34 min flight time and obstacle sensors.",
    installment: "Up to 24 months, as low as Rs. 9,800 per month",
    colorFamily: "Grey",
    storageCapacity: "64GB SD Bundle",
    colors: [{ name: "Grey", code: "#808080" }],
    storageOptions: [],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Rs. 600",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year DJI Warranty",
    },
    seller: {
      name: "DJI Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 44,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl-l1x2-rt_Uv2B3T06ICh-F148Ly3bfr7Eg&s",
    title: "Razer BlackWidow V4 Pro Gaming Keyboard",
    currentPrice: "Rs.44,999",
    originalPrice: "Rs.49,999",
    discount: "-10%",
    rating: 4.8,
    reviews: 1320,
    badge: "Gaming Pick",
    brand: "Razer",
    description:
      "Razer BlackWidow V4 Pro with mechanical switches, RGB lighting, and ergonomic wrist rest.",
    installment: "Up to 6 months, as low as Rs. 7,500 per month",
    colorFamily: "Black",
    storageCapacity: null,
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: [],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-18 Sep",
        price: "Rs. 300",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Razer Warranty",
    },
    seller: {
      name: "Razer Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 45,
    image: "https://retail.com.pk/cdn/shop/files/pixel7pro-b.jpg?v=1707132027",
    title: "Google Pixel 7 Pro 12GB RAM + 256GB",
    currentPrice: "Rs.194,999",
    originalPrice: "Rs.209,999",
    discount: "-7%",
    rating: 4.7,
    reviews: 960,
    badge: "Top Rated",
    brand: "Google",
    description:
      "Google Pixel 7 Pro with Tensor G2 chip, 50MP triple camera system and Android 13.",
    installment: "Up to 24 months, as low as Rs. 8,500 per month",
    colorFamily: "Obsidian Black",
    storageCapacity: "256GB",
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Snow", code: "#ffffff" },
    ],
    storageOptions: ["128GB", "256GB"],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-16 Sep",
        price: "Rs. 400",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Google Store",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 46,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG7tDU5etnNID_fs3fVw1uATcyPfYUDGHsow&s",
    title: "Microsoft Surface Pro 9 (i7, 16GB, 512GB)",
    currentPrice: "Rs.334,999",
    originalPrice: "Rs.359,999",
    discount: "-7%",
    rating: 4.6,
    reviews: 580,
    badge: "Pro Choice",
    brand: "Microsoft",
    description:
      "Surface Pro 9 with Intel i7, 16GB RAM, 512GB SSD and detachable keyboard support.",
    installment: "Up to 36 months, as low as Rs. 14,000 per month",
    colorFamily: "Platinum",
    storageCapacity: "512GB",
    colors: [
      { name: "Platinum", code: "#e5e4e2" },
      { name: "Sapphire", code: "#0f52ba" },
    ],
    storageOptions: ["256GB", "512GB", "1TB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-19 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Microsoft Warranty",
    },
    seller: {
      name: "Microsoft Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 47,
    image:
      "https://discountstore.pk/cdn/shop/files/1_461a815c-5629-485a-8d49-a1c55936a1f0.webp?v=1754123176",
    title: "Kindle Paperwhite Signature Edition",
    currentPrice: "Rs.44,999",
    originalPrice: "Rs.49,999",
    discount: "-10%",
    rating: 4.9,
    reviews: 1740,
    badge: "Readers' Pick",
    brand: "Amazon",
    description:
      "Amazon Kindle Paperwhite Signature Edition with 32GB storage, wireless charging, and warm light.",
    installment: "Up to 6 months, as low as Rs. 7,500 per month",
    colorFamily: "Black",
    storageCapacity: "32GB",
    colors: [{ name: "Black", code: "#000000" }],
    storageOptions: ["8GB", "32GB"],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 12-15 Sep",
        price: "Rs. 200",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Amazon Devices",
      type: "Official Store",
      chatAvailable: true,
    },
  },
  {
    id: 48,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWuczzA8Y-HjAkjsraq1fWXHtaviePWV3SZg&s",
    title: "Beats Studio Buds+ True Wireless Earbuds",
    currentPrice: "Rs.34,999",
    originalPrice: "Rs.39,999",
    discount: "-13%",
    rating: 4.6,
    reviews: 1120,
    badge: "Music Pick",
    brand: "Beats",
    description:
      "Beats Studio Buds+ with active noise cancellation, transparency mode, and 36 hours battery life.",
    installment: "Up to 6 months, as low as Rs. 5,800 per month",
    colorFamily: "Transparent",
    storageCapacity: null,
    colors: [
      { name: "Transparent", code: "#f8f8ff" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Lahore",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 14-17 Sep",
        price: "Rs. 250",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Warranty",
    },
    seller: {
      name: "Beats Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 49,
    image: "https://acom.pk/cdn/shop/files/legion.jpg?v=1688630333",
    title: "Lenovo Legion 5 Gaming Laptop",
    currentPrice: "Rs.239,999",
    originalPrice: "Rs.269,999",
    discount: "-11%",
    rating: 4.7,
    reviews: 1340,
    badge: "Top Gaming",
    brand: "Lenovo",
    description:
      "Lenovo Legion 5 with AMD Ryzen 7, RTX 3060, 16GB RAM and 512GB SSD for powerful gaming.",
    installment: "Up to 24 months, as low as Rs. 10,000 per month",
    colorFamily: "Phantom Blue",
    storageCapacity: "512GB",
    colors: [{ name: "Blue", code: "#000080" }],
    storageOptions: ["512GB", "1TB"],
    deliveryInfo: {
      location: "Karachi",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 16-20 Sep",
        price: "Free",
      },
      cashOnDelivery: false,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Lenovo Warranty",
    },
    seller: {
      name: "Lenovo Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
  {
    id: 50,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO1P476MtKn-UcNYNI9L0G97m4lcbbwmaKzw&s",
    title: "Bose QuietComfort 45 Wireless Headphones",
    currentPrice: "Rs.89,999",
    originalPrice: "Rs.99,999",
    discount: "-10%",
    rating: 4.8,
    reviews: 1580,
    badge: "Best Seller",
    brand: "Bose",
    description:
      "Bose QuietComfort 45 noise cancelling wireless headphones with 24 hours battery life.",
    installment: "Up to 12 months, as low as Rs. 7,500 per month",
    colorFamily: "White Smoke",
    storageCapacity: null,
    colors: [
      { name: "White", code: "#f5f5f5" },
      { name: "Black", code: "#000000" },
    ],
    storageOptions: [],
    deliveryInfo: {
      location: "Islamabad",
      standardDelivery: {
        text: "Standard Delivery",
        time: "Get by 15-18 Sep",
        price: "Rs. 300",
      },
      cashOnDelivery: true,
    },
    warranty: {
      easyReturn: "14 days easy return",
      brandWarranty: "1 Year Bose Warranty",
    },
    seller: {
      name: "Bose Official",
      type: "Flagship Store",
      chatAvailable: true,
    },
  },
];

export default products;
